<a href="https://colab.research.google.com/github/komos0509/Study/blob/main/%EB%A1%9C%EC%A7%80%EC%8A%A4%ED%8B%B1_%ED%9A%8C%EA%B7%80%EB%B6%84%EC%84%9D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!wget https://kimyoungjin06.github.io/2018dbc/lectures/2018DBC_data.zip

--2022-06-27 13:17:35--  https://kimyoungjin06.github.io/2018dbc/lectures/2018DBC_data.zip
Resolving kimyoungjin06.github.io (kimyoungjin06.github.io)... 185.199.109.153, 185.199.110.153, 185.199.108.153, ...
Connecting to kimyoungjin06.github.io (kimyoungjin06.github.io)|185.199.109.153|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1120837 (1.1M) [application/zip]
Saving to: ‘2018DBC_data.zip’

2018DBC_data.zip    100%[===================>]   1.07M  --.-KB/s    in 0.01s   

2022-06-27 13:17:35 (89.0 MB/s) - ‘2018DBC_data.zip’ saved [1120837/1120837]



In [2]:
!unzip 2018DBC_data.zip

Archive:  2018DBC_data.zip
  inflating: [FOR_DISTRIBUTE]test_data.csv  
  inflating: [FOR_DISTRIBUTE]train_data.csv  


In [3]:
!ls

 2018DBC_data.zip		 '[FOR_DISTRIBUTE]train_data.csv'
'[FOR_DISTRIBUTE]test_data.csv'   sample_data


In [4]:
import pandas as pd

In [5]:
data = pd.read_csv('[FOR_DISTRIBUTE]train_data.csv')
data

ID Class   Weekday  ACCESSORIES  AUTOMOTIVE  BAKERY  \
0          2     H  Saturday            0           0       0   
1          3     A    Sunday            0           0       0   
2          4     H    Monday            0           0       0   
3          5     E    Friday            0           0       0   
4          6     G    Friday            0           0       0   
...      ...   ...       ...          ...         ...     ...   
75669  95669     D    Friday            0           0       0   
75670  95670     A    Friday            0           0       0   
75671  95671     I   Tuesday            0           0       0   
75672  95672     C   Tuesday            0           0       0   
75673  95673     I   Tuesday            0           0       0   

       BATH.AND.SHOWER  BEAUTY  BEDDING  BOOKS.AND.MAGAZINES  ...  SEAFOOD  \
0                    0       2        0                    0  ...        0   
1                    0       0        0                    0  ...        0   
2                    0       0        0                    0  ...        0   
3                    0       0        0                    0  ...        0   
4                    1       0        0                    0  ...        0   
...                ...     ...      ...                  ...  ...      ...   
75669                0       0        0                    0  ...        0   
75670                0       0        0                    0  ...        0   
75671                0       0        0                    0  ...        0   
75672                0       0        0                    0  ...        0   
75673                0       0        0                    0  ...        0   

       SERVICE.DELI  SHEER.HOSIERY  SHOES  SLEEPWEAR.FOUNDATIONS  \
0                 0              0      0                      0   
1                 0              0      0                      0   
2                 0              0      0                      0   
3                 0              0      0                      0   
4                 0              0      0                      0   
...             ...            ...    ...                    ...   
75669             0              0      0                      0   
75670             0              0      0                      0   
75671             0              0      0                      0   
75672             0              0      0                      0   
75673             0              0      0                      0   

       SPORTING.GOODS  SWIMWEAR.OUTERWEAR  TOYS  WIRELESS  PHARMACY  
0                   0                   0     0         0         0  
1                   0                   0     0         0         0  
2                   0                   0     0         0         0  
3                   0                   0     0         0         0  
4                   0                   0     0         0         0  
...               ...                 ...   ...       ...       ...  
75669               0                   0     0         0         0  
75670               0                   0     0         0         2  
75671               0                   0     0         0         0  
75672               0                   0     0         0         0  
75673               0                   0     0         0         0  

[75674 rows x 56 columns]

In [6]:
data_list = list(data.columns)

In [7]:
del data_list[0]

data_list

['Class',
 'Weekday',
 'ACCESSORIES',
 'AUTOMOTIVE',
 'BAKERY',
 'BATH.AND.SHOWER',
 'BEAUTY',
 'BEDDING',
 'BOOKS.AND.MAGAZINES',
 'BOYS.WEAR',
 'BRAS...SHAPEWEAR',
 'CANDY..TOBACCO..COOKIES',
 'CELEBRATION',
 'COMM.BREAD',
 'COOK.AND.DINE',
 'DAIRY',
 'DSD.GROCERY',
 'ELECTRONICS',
 'FABRICS.AND.CRAFTS',
 'FINANCIAL.SERVICES',
 'FROZEN.FOODS',
 'GIRLS.WEAR',
 'GROCERY.DRY.GOODS',
 'HARDWARE',
 'HOME.DECOR',
 'HOME.MANAGEMENT',
 'HORTICULTURE.AND.ACCESS',
 'HOUSEHOLD.CHEMICALS.SUPP',
 'HOUSEHOLD.PAPER.GOODS',
 'IMPULSE.MERCHANDISE',
 'INFANT.APPAREL',
 'INFANT.CONSUMABLE.HARDLINES',
 'LADIESWEAR',
 'LAWN.AND.GARDEN',
 'LIQUOR.WINE.BEER',
 'MEAT...FRESH...FROZEN',
 'MEDIA.AND.GAMING',
 'MENSWEAR',
 'OFFICE.SUPPLIES',
 'PAINT.AND.ACCESSORIES',
 'PERSONAL.CARE',
 'PETS.AND.SUPPLIES',
 'PLUS.AND.MATERNITY',
 'PRE.PACKED.DELI',
 'PRODUCE',
 'SEAFOOD',
 'SERVICE.DELI',
 'SHEER.HOSIERY',
 'SHOES',
 'SLEEPWEAR.FOUNDATIONS',
 'SPORTING.GOODS',
 'SWIMWEAR.OUTERWEAR',
 'TOYS',
 'WIRELESS',
 'PHA

In [8]:
# wd = data.Weekday

In [9]:
# Wd = wd.map({'Monday': 0, 'Tuesday': 1, 'Wednesday':2, 'Thursday':3, 'Friday':4, 'Satarday':5, 'Sunday':6 }).values
# WKD = np.asanyarray(Wd)

In [10]:
import os as os
import csv as csv
import numpy as np
import scipy as spy
import sklearn as kit
import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt
from statsmodels.sandbox.regression.predstd import wls_prediction_std
from sklearn.datasets import make_classification
import matplotlib as mpl
import seaborn as sns
import math
from scipy import stats

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [11]:
data.isnull().sum()

ID                             0
Class                          0
Weekday                        0
ACCESSORIES                    0
AUTOMOTIVE                     0
BAKERY                         0
BATH.AND.SHOWER                0
BEAUTY                         0
BEDDING                        0
BOOKS.AND.MAGAZINES            0
BOYS.WEAR                      0
BRAS...SHAPEWEAR               0
CANDY..TOBACCO..COOKIES        0
CELEBRATION                    0
COMM.BREAD                     0
COOK.AND.DINE                  0
DAIRY                          0
DSD.GROCERY                    0
ELECTRONICS                    0
FABRICS.AND.CRAFTS             0
FINANCIAL.SERVICES             0
FROZEN.FOODS                   0
GIRLS.WEAR                     0
GROCERY.DRY.GOODS              0
HARDWARE                       0
HOME.DECOR                     0
HOME.MANAGEMENT                0
HORTICULTURE.AND.ACCESS        0
HOUSEHOLD.CHEMICALS.SUPP       0
HOUSEHOLD.PAPER.GOODS          0
IMPULSE.ME

In [12]:
!pip install sklearn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [13]:
#from sklearn.cross_validation import train_test_split
from sklearn.model_selection import train_test_split 
import numpy as np

In [ ]:
Y = y.map({'A': 0, 'B': 1, 'C':2, 'D':3, 'E':4, 'F':5, 'G':6, 'H':7, 'I':8, 'J':9, 'K':10, 'L':11}).values

for i in range(len(Y)):
  print(Y[i])

In [26]:
X = data.iloc[:,1:]
y = data.loc[:,'Class']
X_train, X_test, y_train, y_test = train_test_split(X, Y, random_state=0)
print(len(X_test), len(y_test))

18919 18919


In [17]:
y_train

array([8, 1, 5, ..., 6, 1, 2])

In [24]:
import collections
collections.Counter(y_train)
collections.Counter(y_test)     

Counter({0: 1984,
         1: 1199,
         2: 2390,
         3: 1895,
         4: 901,
         5: 2042,
         6: 1146,
         7: 1680,
         8: 1935,
         9: 1251,
         10: 902,
         11: 1594})

In [29]:
from sklearn.linear_model import LogisticRegression
#from sklearn.cross_validation import KFold   #For K-fold cross validation
from sklearn.model_selection import KFold
from sklearn.tree import DecisionTreeClassifier, export_graphviz
from sklearn import metrics

classifier = LogisticRegression(random_state=0)
classifier.fit(X_train, y_train)


ValueError: ignored

In [ ]:
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_pred)
print(confusion_matrix)

t = confusion_matrix

[[1670   11  123   45   13   15   10   31   44    1    3   18]
 [  14  779  199    1   10    7    4  102   71    7    1    4]
 [  77   63 2074   30    9   20   24   54   16    0    0   23]
 [  35   11  120 1344   61  206   20    2   13    0    0   83]
 [  22   12   58  192  408   49   23   36   52    9   19   21]
 [  43    5    4  263   32 1407   31   47  110   11   43   46]
 [  21   20  256   10   25   38  606   30   98   21   16    5]
 [  50  104  259    1   20   46   35  861  158  133    9    4]
 [ 108  120   94    0   54   85  171  358  819   92   32    2]
 [   4   29    0    0   11   15   60  121   45  946   20    0]
 [  18    0    1   13  159  403   47   17   43   24  170    7]
 [ 367   21  495  466   34  109   13   14   16    2    1   56]]


In [ ]:
# a = 0
# b = 0
# for j in range(12):
#   for i in range(12):
#     a = t[i][j] + a
# for i in range(12):
#   for j in range(12):
# #     t.replace(t[i][j],t[i][j]/a)
#     t[i][j] = t[i][j]/a   


In [ ]:
print('Accuracy of logistic regression classifier on test set: {:.2f}'.format(classifier.score(X_test, y_test)))

Accuracy of logistic regression classifier on test set: 0.59


In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

             precision    recall  f1-score   support

          A       0.69      0.84      0.76      1984
          B       0.66      0.65      0.66      1199
          C       0.56      0.87      0.68      2390
          D       0.57      0.71      0.63      1895
          E       0.49      0.45      0.47       901
          F       0.59      0.69      0.63      2042
          G       0.58      0.53      0.55      1146
          H       0.51      0.51      0.51      1680
          I       0.55      0.42      0.48      1935
          J       0.76      0.76      0.76      1251
          K       0.54      0.19      0.28       902
          L       0.21      0.04      0.06      1594

avg / total       0.56      0.59      0.56     18919



In [ ]:
# import numpy as np

In [ ]:
# import pandas as pd


# data = pd.read_csv('[FOR_DISTRIBUTE]train_data.csv')
# data_list = list(data.columns)

# del data_list[1]

# import os as os
# import csv as csv
# import numpy as np
# import scipy as spy
# import sklearn as kit
# import pandas as pd
# import statsmodels.api as sm
# import matplotlib.pyplot as plt
# from statsmodels.sandbox.regression.predstd import wls_prediction_std
# from sklearn.datasets import make_classification
# import matplotlib as mpl
# import seaborn as sns
# import math
# from scipy import stats

# from sklearn.cross_validation import train_test_split
# X = data.iloc[:,2:]
# y = data.loc[:,'Class']
# X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

# Y = y.map({'A': 0, 'B': 1, 'C':2, 'D':3, 'E':4, 'F':5, 'G':6, 'H':7, 'I':8, 'J':9, 'K':10, 'L':11}).values

# # import collections
# # collections.Counter(y_train)
# # collections.Counter(y_test)    

# from sklearn.linear_model import LogisticRegression
# from sklearn.cross_validation import KFold   #For K-fold cross validation
# from sklearn.ensemble import RandomForestClassifier
# from sklearn.tree import DecisionTreeClassifier, export_graphviz
# from sklearn import metrics

# classifier = LogisticRegression(random_state=0)
# classifier.fit(X_train, y_train)


# y_pred = classifier.predict(X_test)
# from sklearn.metrics import confusion_matrix
# confusion_matrix = confusion_matrix(y_test, y_pred)
# # print(confusion_matrix)


# print('Accuracy of logistic regression classifier on test set: {:.2f}'.format(classifier.score(X_test, y_test)))